### ISSUE TITLE
Set up code of contact email addresses

### ISSUE THREAD

**Issue by jdudley1123** [dxw/tech-team-rfcs#148]
See [RFC 28](https://github.com/dxw/tech-team-rfcs/blob/main/rfc-028-adopt-a-code-of-conduct.md)

If they already exist, make sure that Dom is no longer the recipient.

**Comment by jdudley1123** [comment]
I've enquired if they already exist

**Comment by Floppy** [comment]
@jdudley1123 what happened on this? I remember you asking about it, what was the outcome?

**Comment by jdudley1123** [comment]
They exist. code-of-conduct@dxw.com currently goes to Dom (so forwards to Dave). I've requested it be changed to go to bob and F.

**Comment by Floppy** [comment]
Nice one. If they exist, then we can probably close this and mark the actions as complete?

**Comment by jdudley1123** [comment]
I think that should wait on the address being updated to no longer go to Dom.

**Comment by Floppy** [comment]
ok

**Comment by jdudley1123** [comment]
Done
