### ISSUE TITLE
Add dxw to the list of Contributor Covenant adopters

### ISSUE THREAD

**Issue by Floppy** [dxw/tech-team-rfcs#150]
See RFC 028 and guidance at https://github.com/EthicalSource/contributor_covenant#adding-a-project-to-the-list-of-adopters

**Comment by Floppy** [comment]
Done in https://github.com/EthicalSource/contributor_covenant/pull/1036

**Comment by snim2** [comment]
> Done in [EthicalSource/contributor_covenant#1036](https://github.com/EthicalSource/contributor_covenant/pull/1036)

This has been marked as done in 370d3dd719391987b3c32619c9bd5ddf34b3bde7, is there anything else that needs to be done before we close this issue?

**Comment by Floppy** [comment]
No, all done!
