### ISSUE TITLE
Management of stale proposals should be clear and straightforward

### ISSUE THREAD

**Issue by tahb** [dxw/tech-team-rfcs#16]
This is one of the proposed principles of a good RFC process: https://github.com/dxw/tech-team-rfcs/pull/3/files#diff-04c6e90faac2675aa89e2176d2eec7d8R107

We need to decide a way to implement the automatic management of stale issues and pull requests.

The Rails template has a proposal to use Probot to mark these as shut for us and it might be something we want to use here too: https://github.com/dxw/rails-template/pull/6

Are there any better ideas? If not, can we add the same settings to this repository?

**Comment by erbridge** [comment]
I think consistency is a good idea, so whatever we decide for other things.

**Comment by erbridge** [comment]
We now state that RFCs open for more than 60 days should be considered stale and closed. I think that resolves this.
