### ISSUE TITLE
Do we want to treat improvements and changes to the repository differently from RFCs

### ISSUE THREAD

**Issue by erbridge** [dxw/tech-team-rfcs#17]
We have a process for dealing with RFCs, but it seems like overkill for repository changes unrelated to specific RFCs. How do we agree on changes to the repo?

My suggestion is to require that they pass the merge constraints (3 reviews, etc.), but otherwise can be merged as soon as they're mergable.

**Comment by jacksonj04** [comment]
This is now supported through #31 and the `tooling` label.

**Comment by pezholio** [comment]
It's a shame we can't override the 3 approvals rule for repos with the `tooling` label

**Comment by erbridge** [comment]
We can if we make a workflow check for them instead of branch protection.
