### ISSUE TITLE
Should this be a private repository?

### ISSUE THREAD

**Issue by tahb** [dxw/tech-team-rfcs#2]
We try to follow Government design principle [Make things open it makes things better](https://www.gov.uk/guidance/government-design-principles#make-things-open-it-makes-things-better) by default and for that reason this repository was created as a public one. 

Whilst we should be free to make this private we should be clear on the reasons why we might do so.

Benefits of having our process and decisions in the open:

- others can learn from us and spend more their time making things better for users
- it allows us to share our thinking and rationale on our technical decisions, doing so publicly as well as privately can increase trust and empathy with more people
- with the potential for the world watching the bar is raised
- being open from the start ensures that there is less risk to us should a future team decide to make it public

The intention of this issue is the document the decision made so far and to signal that we have a question to answer as a tech team. The hope is that by answering it we will gain a better shared understanding and be able to document our reasoning if we decide to change.

Which ever way we decide we should add this as an ADR too.

**Comment by erbridge** [comment]
My main concern about it being public is that it means we can't discuss sensitive information that might guide our discussions or RFCs. For instance, we might want to talk about a leak that occured and how we want to change our practices to avoid that. If this is public, it means we have to talk around the issue, making it harder to understand out of context.

**Comment by pezholio** [comment]
I'm usually very anti private repos, but I don't think it's the end of the world to make this private, as long as decisions that are made get reflected in the Playbook

**Comment by Floppy** [comment]
Like @pezholio, I don't like private repos, but @erbridge makes a good point about being able to describe reasoning with candour and accuracy in the doc, but even more importantly discuss in PRs, so private is probably the right choice here.

**Comment by lawrence-dxw** [comment]
I don't understand why this repository should be treated any differently from a privacy point of view than any of our other public repositories. We, as developers at dxw, make technical decisions every day, and we justify them, and we do so publicly. 

Has anybody encountered the described problem in the context of day-to-day development work on a public repository; that is, have there been times when you weren't able to write a commit message or pull request comment that was as detailed as you'd have liked?

**Comment by erbridge** [comment]
This is different from projects in that it's a place to talk about and document decisions about the ways we work in general as developers. This isn't so much about technical decisions as much as about decisions _about_ technical decisions, and other things. As such, it would be useful to be able to have discussions like "we had this breach in this client project, and we need to change the way we handle secrets to avoid this happening again" without worrying about exposing our clients. I think we also want to be able to talk about "we had this issue working with this client, and we want to change X to avoid or reduce the impact of that" without publicly dragging a client's name through the mud.

**Comment by erbridge** [comment]
I'm not sure. My instinct is private from the start because there's cognitive load involved in being aware of what's ok to talk about and what isn't, and making it private when "needed" is an information leaking event that would also require a discussion about _why_ we need to make it private, and this is supposed to be the place to discuss such things.

**Comment by tahb** [comment]
Even as the author I'd like to state my opinion: I think this repository should remain public for now.

I agree with what Lawrence has said. We do make technical decisions in the open every day and some of these can involve difficult conversations. I wish for our culture to continue in the direction of being open and honest where at all possible and that we should work hard to see if we can, whether it be a simple issue such as coding style or complex issue like how we manage grievances. 

That said, I do acknowledge there are edge cases such as incidents and their details that should remain private. I think there are other ways to support these scenarios that are worth exploring before taking the big decision to hide everything:

- retrospectives would provide a forum for people who had this issue to raise it and say "I felt unable to talk about this publicly". We can use this as a way to decide what actions to take. One of these actions may well be to make it private
- for a topic we might mark as sensitive or that we judge are too sensitive to be discussed on GitHub we could take a decision to continue the discussion in person at a tech-forum. My instinct is that these cases will be less common so even a deliberate meeting wouldn't be unreasonable. We could conclude the meeting by posting a 'safe' summary of the debate online

I worry that starting as private will mean it will forever have to remain private due to content being added under that condition. This we will effectively stop us from changing our mind on this issue later and going from private to public.

**Comment by tahb** [comment]
This issue has been open for 23 days and I've made 3 calls for feedback during that time. It has captured some opinions for and against. Thank you for your contributions. 

I don't believe there is a consensus to make this repository private. 

Arguably I should have raised this initially as an RFC not an issue, since I was in fact requesting comment. I will translate this issue into an RFC. This way the team can easily find out why this repository is public in future as hunting through closed issues will make it hard to find.

**Comment by tahb** [comment]
https://github.com/dxw/tech-team-rfcs/pull/18
