### ISSUE TITLE
How should this connect with the rest of our documentation?

### ISSUE THREAD

**Issue by tahb** [dxw/tech-team-rfcs#4]
As a tech team we have 2 primary sources of information on how we work:

1. [Playbook](https://playbook.dxw.com/#/)
2. [Ops docs](https://git.govpress.com/ops/docs)

This repository proposes the addition of a third which risks:

- making things harder to find
- duplication and lack of clarity on how we do things
- being overwhelming to new team members

As the Playbook is public, [if we decide to make this repository private](https://github.com/dxw/developer-rfcs/issues/2) then this separate repository might make sense.

- are there any other risks?
- presuming this repository remains public, how can we connect this to the rest of our documentation to mitigate these risks?

**Comment by erbridge** [comment]
I think this repo is a log of decisions we have made. The outcome of those decisions might be to make changes elsewhere.

**Comment by lawrence-dxw** [comment]
Agree with @erbridge. Furthermore, I'd say that we should agree that the two linked documents should be considered the source of truth. Meaning that if something's there, then it's what we do.

That leaves the question of whether _every_ decision should result in an update to one of those two documents, or whether the RFCs repo acts as a fallback for something unspecified by the guides.

**Comment by erbridge** [comment]
I think the RFCs are about documenting change and decisions. An RFC alone is not sufficient to actually put them into practice. I actually suggest adding a section to the template that explains what the output of the RFC would be if accepted, i.e. what other document or project would be changed as a result.

**Comment by erbridge** [comment]
Closing this as resolved by the modification to the template in #10.
