### ISSUE TITLE
What happens to the Rails Template?

### ISSUE THREAD

**Issue by tahb** [dxw/tech-team-rfcs#5]
We have a [GitHub repository that serves as a Rails template](https://github.com/dxw/rails-template). This repository has some initial pull requests that are attempting to make decisions and to set up agreed standards within the code base. This now conflicts with this repository and risks duplicating our attention and efforts.

Using a template will offer benefits:

- quickly start a new repository with a set of default tooling
- projects will start being built in a more consistent way, making it easier to support
- a complete history of architecture decision records can help stakeholders understand the service. Stakeholders can include clients, assessors, pen testers and future teams. With better understanding around on how it was built, more informed decisions can be made about it's future
- consistent tooling and ADRs will better support new developers rotated on
- configuration files can be included to improve routine tasks. For example Probot can be used to ensure the right teams have access. GitHub actions can be used to provide an out of the box deployment pipeline to Heroku 

To keep the benefits of using this template I propose an output of an accepted RFC is to create an ADR in the appropriate template. This will allow templates for other languages to exist such as wordpress-template.

Does anyone else have an idea of how we can solve this?

**Comment by erbridge** [comment]
I think we have a division of concerns. Maybe RFC1 is to propose that changes to `rails-template` are documented in `rails-template` through PRs and ADRs? This repo seems better suited to changes in the way we work than the templates we use.
