### ISSUE TITLE
What does consensus mean and how do we reach it?

### ISSUE THREAD

**Issue by tahb** [dxw/tech-team-rfcs#8]
# Reaching consensus

In the [existing RFC process](https://github.com/dxw/developer-rfcs/commit/71d38e15684778ce7d42183c656a009aa77f9352) we refer to the term consensus which was language used with the original GOV.UK version.

## What do we think of as consensus? 

- Have we reached consensus when there is a majority or approvals? Using a tie-breaker if required.
- Have we reached consensus when *all* active participants are in favour? Should a single preference of SHOULD NOT be able block a decision?

## How does reaching consensus change depending on the type of decision being made?

Different types of decision warrant different levels of attention. For instance a decision to use a RFC process should require more agreement than a decision to use double spaces for indentation.

At present we have a minimum approval count of 3 on pull requests. To me this seems a safe and reasonable minimum given the size of our team for any decision.

How should we categorise our decisions so that important ones require more of the tech team to approve? 

- Is the authors judgement enough to categorise so that approvals are weighted: small=3, medium=1/3, large=2/3
- Should we have a new step in the process where we run the proposal by another person to check if this is a small or big shaped thing?
- Any other ideas?

**Comment by Floppy** [comment]
I have a thing that does exactly this sort of voting on PRs; I could enable it for this repo, see how it goes?

**Comment by erbridge** [comment]
My personal take on consensus, is that if someone is "blocking" an RFC, their reason for blocking it should be resolved before we can consider it accepted. Blocking here is reserved as an action which someone should only use if they think that an RFC **should not** be accepted under any circumstances, unless the reason for blocking is resolves. There should be a different way for someone to say that they disagree, but to not block the change.

If we were a truly flat organization, I would argue strongly that any blocked RFCs should essentially be prevented from being accepted until they became unblocked (maybe requiring 2 blockers who are refusing to unblock). However, we're not flat, so I think that we can have an escape hatch of Dom (and maybe others) as tie-breaker.

It terms of how we integrate this with GitHub, I suggest that we set up rules that require at least 3 green reviews and fewer than 2 red reviews to merge a PR. If red reviewers change their minds, they need to re-review as white or green to unblock. If the PR is blocked, and the tie-breaker wants to overrule the block, they would then dismiss the blocking red reviews (which can be done from the three dot menu in the approvals list), so it can be merged.

It's worth reading the Wikipedia article on consensus, particularly:
- https://en.wikipedia.org/wiki/Consensus_decision-making#Blocking_and_other_forms_of_dissent
- https://en.wikipedia.org/wiki/Consensus_decision-making#Process_models

**Comment by erbridge** [comment]
I'd suggest that this question is no longer necessary. We've been doing this for nearly 2.5 years and haven't had any issues reaching consensus. We can reopen this discussion if we do.
